docs: update README.md
rudderlabs/rudder-sdk-ruby-sync pull request #7
Opened 2022-12-27 08:20 UTC by ameypv-rudder

## Description of the change

> Updated Ruby SDK repo readme 

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-12-27 09:10 UTC, pallabmaiti requested changes

2022-12-27 09:10 UTC, pallabmaiti commented on README.md
> +  gzip: false,  # set to true to enable Gzip compression
```suggestion
  gzip: true,  # set to false to disable Gzip compression
```

2022-12-27 09:10 UTC, pallabmaiti commented on README.md
> +  gzip: false, // set to true to enable Gzip compression
```suggestion
  gzip: true, // set to false to disable Gzip compression
```

2022-12-27 09:10 UTC, pallabmaiti commented on README.md
> +| Note: Gzip requires `rudder-server` version 1.4 or later. |
Can you bring this to top & if possible more eye-catching way?

2022-12-29 05:52 UTC, pallabmaiti approved these changes

2023-01-06 10:23 UTC, ameypv-rudder commented
Closing this PR as a fresh PR is raised to avoid merge conflicts.

2023-01-06 10:23 UTC, closed without merging